const FIREBASE_PUBLIC_ENV_MAP = {
  NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
    process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  NEXT_PUBLIC_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
};

const REQUIRED_FIREBASE_PUBLIC_ENV_KEYS = [
  "NEXT_PUBLIC_FIREBASE_API_KEY",
  "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
  "NEXT_PUBLIC_FIREBASE_PROJECT_ID",
  "NEXT_PUBLIC_FIREBASE_APP_ID"
] as const;

export type FirebasePublicEnvKey = keyof typeof FIREBASE_PUBLIC_ENV_MAP;

function isPlaceholderValue(value: string) {
  const normalized = value.trim().toLowerCase();
  return (
    normalized.length === 0 ||
    normalized.includes("your-") ||
    normalized.includes("replace-")
  );
}

export function getMissingFirebasePublicEnvKeys(): FirebasePublicEnvKey[] {
  return REQUIRED_FIREBASE_PUBLIC_ENV_KEYS.filter((key) => {
    const value = FIREBASE_PUBLIC_ENV_MAP[key];
    return typeof value !== "string" || isPlaceholderValue(value);
  });
}

export const firebaseConfig = {
  apiKey: FIREBASE_PUBLIC_ENV_MAP.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: FIREBASE_PUBLIC_ENV_MAP.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: FIREBASE_PUBLIC_ENV_MAP.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: FIREBASE_PUBLIC_ENV_MAP.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: FIREBASE_PUBLIC_ENV_MAP.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: FIREBASE_PUBLIC_ENV_MAP.NEXT_PUBLIC_FIREBASE_APP_ID,
  measurementId: FIREBASE_PUBLIC_ENV_MAP.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
};
